### ISSUE TITLE
App doesn't install correctly.

### ISSUE THREAD

**Issue by adamrharrison** [Shopify/embedded-app-example#21]
I am having some trouble installing the app. I followed the steps in the readme and when the app is installed all it contains is the title of the app and a blue loading bar that never completes. Anything i missed while installing ?

**Comment by kmcphillips** [comment]
There are a number of things that could be amiss here. Likely having to do with API key or host name. Look in your browser's JS console for errors and hints.

This repo is not actively monitored for support. Your best bet is our forums:
https://ecommerce.shopify.com/c/partners-technical
