### ISSUE TITLE
myshopify_domain field is missing from shopify_app.yml.example

### ISSUE THREAD

**Issue by berkcaputcu** [Shopify/embedded-app-example#23]
Since https://github.com/Shopify/shopify_app/pull/121 introduced configurable domain, the yml file needs to set that field too. It could default to `myshopify.com`

**Comment by kmcphillips** [comment]
That field should be optional and default to the correct value as it is only needed for internal development. If it does not already work like that, it is a bug. cc @ilikeorangutans @awd

**Comment by berkcaputcu** [comment]
it didn't have (or had the wrong) default value and omniauth shopify strategy didn't like the domain that was passed to it.

**Comment by IslamAzab** [comment]
It defaults to `""` and that did make it work.
