### ISSUE TITLE
Example fails due to no ssl on localhost

### ISSUE THREAD

**Issue by playmakers** [Shopify/embedded-app-example#26]
Hey

I followed the example at http://shopify.github.io/embedded-app-example. It all worked out, except the last step, where the esdk request my local machine. I get:

```
 Mixed Content: The page at 'https://test.myshopify.com/admin/apps/66a36bb2201bc888c602cbffaaf91c2a' was loaded over HTTPS, but requested an insecure resource 'http://localhost:3000/?hmac=0d59069f8b36a773fdb6c2d72a5b9274a76dfaae019ce17…hopify.com&signature=4a3b1f06fa4c17caa2046041910c66cd&timestamp=1425508906'. This request has been blocked; the content must be served over HTTPS.
```

well, I don't have ssl on my local machine running, so what can I do?

**Comment by kmcphillips** [comment]
As stated in the docs, you have to develop over SSL to avoid those mixed content warnings.

You can use an SSL forwarding service like http://forwardhq.com/ or some other one. Or you can try to tell your browser to ignore mixed content for that site, but I had very bad luck getting that to work reliably.

**Comment by playmakers** [comment]
thx, I just expected http://shopify.github.io/embedded-app-example to be a working example, better to mention/add link to the SSL documentation on there too, otherwise no-one will reach the last step `You will be prompted to install the application and will be redirected to the embedded Shopify environment once installed.`
