### ISSUE TITLE
Needs more documentation

### ISSUE THREAD

**Issue by abreckner** [Shopify/embedded-app-example#28]
Hello, 
It took me a while to get this working because of the following reasons

1) It wasn't specified that you need a Shopify Partner account to use this. I created a private app and was using those credentials which didn't work

2) You should point out that once this is running people will run into the mixed content issue when working off their localhost (i.e. localhost is http and shopify is https). In Chrome you need to click on the shield and "allow unsafe scripts" to get this to work.

Thanks

Tony Breckner

**Comment by kmcphillips** [comment]
Hello. Thank you for your feedback.

The first page of the "Getting Started" section of the documentation for the Embedded App SDK explains how to activate an app in your partner account, and the SSL requirement. There is a call out box specifically explaining how to develop locally with mixed content. These docs are linked to in the README.

https://docs.shopify.com/embedded-app-sdk/getting-started

This short README is not intended to be a replacement for the documentation on the SDK.

If you'd like, I can add some extra wording to make that clearer.

**Comment by kmcphillips** [comment]
Fixed via e6b365a9f32881eac3ab472c40c1c337ef1b2279
