### ISSUE TITLE
Still doesn't work after getting my localhost on https

### ISSUE THREAD

**Issue by ajmalafif** [Shopify/embedded-app-example#30]
I've set up my localhost to use `https`:

<img src="https://www.evernote.com/l/AFlvJt8Sz5BBor5yYlerpFr0MpnXLbnPd48B/image.png"/>

I've change the redirect_uri to this format:
`https://localhost.dev/auth/shopify/callback`

and add this on line 10 inside `omniauth.rb` file:
`redirect_uri = "https://bee.dev/auth/shopify/callback"`

but when I click on the app within Shopify it gives me this error: 

`A static HTML page can contain a simple dependency free script to set the top bar to a 500 server error. This page can be found in 'public/500.html'.`

So I'm not sure if the example code is broken or I'm missing some steps? Or it actually ends there?

**Comment by celsodantas** [comment]
you should not use any `localhost` URI for any redirect in Shopify, it's a blacklisted path. You must use a public URI. 

I suggest the use of a port forwarding service like ngrok.

**Comment by celsodantas** [comment]
Please use Shopify forums to ask for help: https://ecommerce.shopify.com/c/shopify-apis-and-technology

=)
