### ISSUE TITLE
Oauth error invalid_request: Could not find Shopify API application with api_key

### ISSUE THREAD

**Issue by micahbolen** [Shopify/embedded-app-example#32]
I've followed all of the installation instruction including creating a `.env` file and adding my app's API key and secret.  I am able to start the app with `bundle exec rails s`, but I'm getting an error when I navigate to this URL:

`http://localhost:3000/login?shop=alivechat-dev.myshopify.com`

I am redirected to the following URL:

`https://alivechat-dev.myshopify.com/admin/oauth/authorize?client_id=&redirect_uri=http%3A%2F%2Flocalhost%3A3000%2Fauth%2Fshopify%2Fcallback&response_type=code&scope=read_customers%2C+read_orders%2C+write_products&state=6a497fac520f74f10f6cdf6a5f3e19b7203d37490affd467`

..and see the following message on this page:

> Oauth error invalid_request: Could not find Shopify API application with api_key

I also thought I already setup my dev shop and app settings properly.  Any ideas?  Let me know if you need any other details (such as request/response headers and/or query string parameters) and/or point me in the right direction.  I did notice that the `client_id` query string parameter on the aforementioned 400 error page was blank, but I'm not sure why.

**Comment by kmcphillips** [comment]
@micahbolen Sorry, but this repo is not used for support requests. Can you redirect your questions to our forums:

https://ecommerce.shopify.com/forums
