### ISSUE TITLE
Existing button callbacks aren't unbound upon ShopifyApp.Bar.initialize

### ISSUE THREAD

**Issue by jonjaques** [Shopify/embedded-app-example#33]
Apologies if this isn't the right place to report this. I'm building single-page embedded app with the `ShopifyApp` API and noticed something funny with the navigation. 

I have a React component `<ShopifyBar title="Stuff"/>`, that dumbly (as in many times) calls `Bar.initialize` to update the header as views change. However I notice that after I navigate around a few times, my `button` callbacks are starting to fire many times. 

The error is partially on my part, because I could be smarter about using `setTitle` or `setIcon`, but I think `initialize` should probably unbind any existing handlers when called more than once.. Maybe? Especially given this is the only way to update buttons.

I can see why this isn't a huge problem for most apps, but it's so convenient to just call `initialize` and update the whole thing at once. I'd appreciate any ideas you have.

**Comment by kevinhughes27** [comment]
Thanks for the issue. Can you re-open on https://github.com/Shopify/shopify_app
