### ISSUE TITLE
Not loading

### ISSUE THREAD

**Issue by tynichol** [Shopify/embedded-app-example#34]
You will find my heroku log below. It seems to load everything fine and then it says something went wrong on the web page. No error messages from the logs?! Anyone have this issue?

<code>at=info method=GET path="/auth/shopify/callback?code=fe7f9901e59dfdf23fa612848185da99&hmac=40469c6ebb75f8ef44af936ff0f0af7c28627e62c63fcca2948bc88f63ad3ea3&shop=mati-and-the-bug.myshopify.com&signature=03377f69f4b21787bb21ed9064cd0e5e&state=56d45a0f1f1a3372ddec72b06b59d76b1df0e13a06d3a8d4&timestamp=1444423567" host=infinite-waters-2523.herokuapp.com request_id=4a6f1439-011a-49d0-963a-ef06274bb69a fwd="104.7.208.77" dyno=web.1 connect=1ms service=363ms status=500 bytes=1669
2015-10-09T20:46:08.408479+00:00 heroku[router]: at=info method=GET path="/favicon.ico" host=infinite-waters-2523.herokuapp.com request_id=ad7af7e6-0680-4743-bdc2-88f28cfe80a9 fwd="104.7.208.77" dyno=web.1 connect=1ms service=3ms status=200 bytes=143</code>

**Comment by dbnoble** [comment]
@tynichol it looks like you need to add https://infinite-waters-2523.herokuapp.com/auth/shopify/callback to the Redirection URL section of your app in the Shopify Partners Dashboard

**Comment by kevinhughes27** [comment]
closing this issue. If its still an issue please open on https://github.com/Shopify/shopify_app
