### ISSUE TITLE
Issue with ShopifyApp.ready()

### ISSUE THREAD

**Issue by reggi** [Shopify/embedded-app-example#9]
It doesn't run sometimes. I can't get it to run within `requirejs` and I can't more obviously I can't get it to run within `$(document).ready(function() `. I don't feel safe leaving all of the `ShopifyApp` related functions out in the open.

**Comment by jonjaques** [comment]
Using this with Webpack & Babel - `ready()` callback never fires. Other methods work okay though if called after `init()`

**Comment by kevinhughes27** [comment]
Closing. If this is still an issue please re-open on https://github.com/Shopify/shopify_app
